///////////////////////////////////////////////////////////
//  Atividade.cs
//  Implementation of the Class Atividade
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	/// <summary>
	/// A Atividade.
	/// </summary>
	public class Atividade {
		public int Id { get; set; }
		[Display(Name = "Título")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		public ICollection<Atitude> Atitudes { get; set; }
		[Display(Name = "Competências")]
		public ICollection<Competencia> Competencias { get; set; }
		public Unidade Unidade { get; set; }
		public Trilha Trilha { get; set; }
		public Papel Papel { get; set; }
	}//end Atividade

}//end namespace br.edu.up.mtx.domain