///////////////////////////////////////////////////////////
//  Bloom.cs
//  Implementation of the Class Bloom
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Bloom {
		public int Id { get; set; }
		[Display(Name = "Código")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Nível")]
		public string Nivel { get; set; }
	}//end Bloom

}//end namespace br.edu.up.mtx.domain