///////////////////////////////////////////////////////////
//  Conteudo.cs
//  Implementation of the Class Conteudo
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Conteudo {
		public int Id { get; set; }
		[Display(Name = "Título")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		public ICollection<Unidade> Unidades { get; set; }
		public ICollection<Conhecimento> Conhecimentos { get; set; }
		[Display(Name = "Específicos")]
		public ICollection<Conteudo> Especificos { get; set; }
		public Conteudo Geral { get; set; }
		public Trilha Trilha { get; set; } 

	}//end Conteudo

}//end namespace br.edu.up.mtx.domain