///////////////////////////////////////////////////////////
//  Curso.cs
//  Implementation of the Class Curso
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using br.edu.up.mtx.domain;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	
	public class Curso {
		public int Id { get; set; }
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		public Escola Escola { get; set; }
		public Modalidade Modalidade { get; set; }
		public TipoDeCurso Tipo { get; set; }
		public ICollection<PerfilDoCurso> PerfisDoCurso { get; set; }
		public ICollection<Matriz> Matrizes { get; set; }
		[Display(Name = "% max atividades EAD")]
		public int PercMaxAtividadeDistancia { get; set; }
		[Display(Name = "Horas min estágio")]
		public int CargaHorasMinEstagio { get; set; }
		[Display(Name = "Horas min curso")]
		public int CargaHorasMinCurso { get; set; }
		[Display(Name = "% max estágio monitorado")]
		public int PercMaxEstagioAC { get; set; }
	}//end Curso

}//end namespace br.edu.up.mtx.domain