///////////////////////////////////////////////////////////
//  DCN.cs
//  Implementation of the Class DCN
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class DCN {
		public int Id { get; set; }
		[Display(Name = "Identificação")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		public ICollection<Matriz> Matrizes { get; set; }
		public ICollection<Diretriz> Diretrizes { get; set; }
	}//end DCN

}//end namespace br.edu.up.mtx.domain