///////////////////////////////////////////////////////////
//  Diretriz.cs
//  Implementation of the Class Diretriz
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Diretriz {
		public int Id { get; set; }
		[Display(Name = "Identificação")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Competências")]
		public ICollection<Competencia> Competencias { get; set; }
		public DCN DCN { get; set; }
	}//end Diretriz

}//end namespace br.edu.up.mtx.domain