///////////////////////////////////////////////////////////
//  Disciplina.cs
//  Implementation of the Class Disciplina
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Disciplina {
		public int Id { get; set; }
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Período")]
		public Periodo Periodo { get; set; }
		[Display(Name = "Unidades da discplina")]
		public ICollection<UnidadeDaDisciplina> UnidadesDaDisciplina { get; set; }
		public Trilha Trilha { get; set; }
	}//end Disciplina
}//end namespace br.edu.up.mtx.domain