///////////////////////////////////////////////////////////
//  Habilidade.cs
//  Implementation of the Class Habilidade
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Habilidade {
		public int Id { get; set; }
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Competência")]
		public Competencia Competencia { get; set; }
	}//end Habilidade

}//end namespace br.edu.up.mtx.domain