///////////////////////////////////////////////////////////
//  Matriz.cs
//  Implementation of the Class Matriz
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:54
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Matriz {
		public int Id { get; set; }
		[Display(Name = "Identificação")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Código")]
		public string Codigo { get; set; }
		[Display(Name = "Períodos")]
		public ICollection<Periodo> Periodos { get; set; }
		public ICollection<Trilha> Trilhas { get; set; }
		[Display(Name = "Papéis")]
		public ICollection<Papel> Papeis { get; set; }
		public Curso Curso { get; set; }
		public DCN DCN { get; set; }
	}//end Matriz

}//end namespace br.edu.up.mtx.domain