///////////////////////////////////////////////////////////
//  Perfil.cs
//  Implementation of the Class Perfil
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:55
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Perfil {
		public int Id { get; set; }
		[Display(Name = "Título")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Competências")]
		public ICollection<Competencia> Competencias { get; set; }
		[Display(Name = "Papéis")]
		public ICollection<Papel> Papeis { get; set; }
		[Display(Name = "Perfis do curso")]
		public ICollection<PerfilDoCurso> PerfisDoCurso { get; set; }
	}//end Perfil

}//end namespace br.edu.up.mtx.domain