///////////////////////////////////////////////////////////
//  Unidade.cs
//  Implementation of the Class Unidade
//  Generated by Enterprise Architect
//  Created on:      01-abr-2020 22:21:55
//  Original author: Geucimar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace br.edu.up.mtx.domain {
	public class Unidade {
		public int Id { get; set; }
		[Display(Name = "Título")]
		public string Nome { get; set; }
		[Display(Name = "Descrição")]
		public string Descricao { get; set; }
		[Display(Name = "Código")]
		public string Codigo { get; set; }
		[Display(Name = "Conteúdos")]
		public Conteudo Conteudos { get; set; }
		public ICollection<Atividade> Atividades { get; set; }
		[Display(Name = "Unidades da disciplina")]
		public ICollection<UnidadeDaDisciplina> UnidadesDaDisciplina { get; set; }
		public Trilha Trilha { get; set; }
	}//end Unidade

}//end namespace br.edu.up.mtx.domain